### ISSUE TITLE
GrabableObject softlock

### ISSUE THREAD

**Issue by Aeniema** [Hypick122/BetterShotgun#15]
### Describe the bug

Can create GrabableObject softlock. Gives shovels reload tooltip. 

### Reproducible Test

I actually don't know, it happens when picking up a second shotgun at same time someone as was trying to grab.

### Anything else?

n/a

**Comment by Hypick122** [comment]
Have you changed any parameters in the config?

**Comment by Aeniema** [comment]
AmmoCheckAnimation=false
ReloadKeybind=r
Rarity=-1
Also removed the sale of it from the store.

**Comment by Hypick122** [comment]
If I understood everything correctly, then in version [1.4.0](https://github.com/Hypick122/BetterShotgun/commit/da0450e3193922dd1f726e2210ccea6538c32ed6#diff-a224c37cac706a2907071a4ebb720c8135985528bba8bd40138f702fdac3e33cR159) this bug was fixed
