### ISSUE TITLE
ReloadKeybind not functionally changing in v1.4.0

### ISSUE THREAD

**Issue by Slendykins** [Hypick122/BetterShotgun#17]
### Describe the bug

Changing the ReloadKeybind character does not seem to change the actual keybind in version 1.4.0, it does change the UI text though.

### Reproducible Test

Changing the keybind key in 1.4.0

### Anything else?

I used the key C but this works fine in 1.3.0, R is used by ThrowEverything :)

**Comment by Hypick122** [comment]
Bug fixed in [1.4.1](https://github.com/Hypick122/BetterShotgun/commit/3c5068922c52afc69805fb825c1aa276a731398d#diff-5ba2d37902b4e4dc3f9e1dd0f4d38265132c9771806f1b915626fe8578828622R57)

**Comment by Slendykins** [comment]
Hey Hypick!

Looks like this issue has resurfaced again, Keybind seems to be E despite being changed, here's a few screenshots;

![image](https://github.com/Hypick122/BetterShotgun/assets/155987752/a4a35c53-b1ed-4d34-87f5-41c343db9804)
![image](https://github.com/Hypick122/BetterShotgun/assets/155987752/d75f5b72-c1c6-482e-931b-b8621edce083)
![image](https://github.com/Hypick122/BetterShotgun/assets/155987752/eb16f699-c642-48e5-8847-ca89235dbd8c)
