### ISSUE TITLE
Checking bullets when used with LCAmmoCheck will make the gun invisible

### ISSUE THREAD

**Issue by JiuKe037** [Hypick122/BetterShotgun#24]
### Describe the bug

Checking bullets when used with LCAmmoCheck will make the gun invisible

### Reproducible Test

I tried to lower the versions of these two MODs, but the result remained the same

**Comment by JiuKe037** [comment]
By the way, I have no problem using LCAmmoCheck OLD

**Comment by Hypick122** [comment]
If you delete BetterShotgun, will AmmoCheckAnimation(_OLD) work normally? And have you disabled AmmoCheckAnimation in the configuration? Also, please send a list of installed mods

**Comment by Hypick122** [comment]
This problem is related to the LCAmmoCheck mod, not BetterShotgun
