### ISSUE TITLE
ReloadKeybind not rebinding again

### ISSUE THREAD

**Issue by Slendykins** [Hypick122/BetterShotgun#25]
### Describe the bug

Hey Hypick!

Looks like the ReloadKeybind issue has resurfaced again, Keybind seems to be E despite being changed;

![image](https://github.com/Hypick122/BetterShotgun/assets/155987752/824cc272-a14f-4d09-829b-0dbf71a0e12b)

### Reproducible Test

Changing the keybind has no effect in the config

**Comment by Hypick122** [comment]
Do you have ReservedItemSlotCore installed? The latest version adds a check and automatically sets E if this mod is installed

**Comment by Slendykins** [comment]
Oh yeah I've got core but don't have the reserved weapon slot, only spraypaint and flash.

Maybe the check should be for ReservedWeaponSlot instead of core?

**Comment by Hypick122** [comment]
I will try to fix the problem with this mod in a future update and maybe remove the check.
