### ISSUE TITLE
Configs not sync

### ISSUE THREAD

**Issue by ashenwarg** [Hypick122/BetterShotgun#28]
### Describe the bug

Can you possibly add in config sync? 

### Reproducible Test

na

**Comment by Hypick122** [comment]
Config synchronization was added in version 1.4.4. It would be nice if you could check it out.

**Comment by ashenwarg** [comment]
> Config synchronization was added in version 1.4.4. It would be nice if you could check it out.

The configs do not sync with update

**Comment by Hypick122** [comment]
A little later, I will replace the synchronization with CSync, which should solve this problem.

**Comment by Hypick122** [comment]
In version 1.4.5, I replaced synchronization with CSync
