### ISSUE TITLE
Sync Configs (copy)

### ISSUE THREAD

**Issue by GracefulUni** [Hypick122/BetterShotgun#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Can we get the configs to be synced by host? I see there was a request in the closed tab but it seems that the configs arent syncing still with the host.
There is a mod "https://thunderstore.io/c/lethal-company/p/Sigurd/CSync/" I assume authors need add this or something?

**Comment by Hypick122** [comment]
I will replace the sync with CSync later. And I will close this issue as a copy of #28
