### ISSUE TITLE
Shotgun related mods

### ISSUE THREAD

**Issue by dannycreations** [Hypick122/BetterShotgun#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Would be nice if you can also implement this
https://thunderstore.io/c/lethal-company/p/axd1x8a/LCAmmoCheck/
https://thunderstore.io/c/lethal-company/p/Hexi/HexiBetterShotgun/
https://thunderstore.io/c/lethal-company/p/Horsey4/ShotgunFix/
https://thunderstore.io/c/lethal-company/p/kim_bird/ShotGunMissFireFix/

**Comment by Hypick122** [comment]
Maybe in the future I will add functionality from these mods

**Comment by Hypick122** [comment]
In version 1.1.0 (https://github.com/Hypick122/BetterShotgun/commit/acd8d3a1319e280b597023e2e69c3802aed67dfc) I added functionality from [ShotGunMissFireFix](https://thunderstore.io/c/lethal-company/p/kim_bird/ShotGunMissFireFix/) and [LCAmmoCheck](https://thunderstore.io/c/lethal-company/p/axd1x8a/LCAmmoCheck/) (still worse than the original)

**Comment by dannycreations** [comment]
> In version 1.1.0 ([acd8d3a](https://github.com/Hypick122/BetterShotgun/commit/acd8d3a1319e280b597023e2e69c3802aed67dfc)) I added functionality from [ShotGunMissFireFix](https://thunderstore.io/c/lethal-company/p/kim_bird/ShotGunMissFireFix/) and [LCAmmoCheck](https://thunderstore.io/c/lethal-company/p/axd1x8a/LCAmmoCheck/) (still worse than the original)

i will test it and report if found some issues
also found other shotgun fix, and i think this one is more stable
https://thunderstore.io/c/lethal-company/p/Zaggy1024/NutcrackerFixes/

**Comment by dannycreations** [comment]
@Hypick122 here are some tweak that you may consider to change
+ Change ShotgunShell store name from "Ammo" to "Shells"

Everything that changing vanilla behavior should be default disable
MisfireOff and ShowAmmoCount is okay to be default enable
+ Shell Rarity Default to -1
+ ReloadKeybind Default to E
+ AmmoCheckAnimation Default to false

also you can close this issue when AmmoCheckAnimation already stable enough or at any time
HexiBetterShotgun & ShotgunFix i'm consider as optional since their implement is still stable enough
and thanks for your work, Great mod!

**Comment by Hypick122** [comment]
The name in the store was returned back in the latest version, and AmmoCheckAnimation was set to false by default
