### ISSUE TITLE
Code running when CheckAmmoAnimation is disabled

### ISSUE THREAD

**Issue by JuanCalle1606** [Hypick122/BetterShotgun#7]
[This code](https://github.com/Hypick122/BetterShotgun/blob/acd8d3a1319e280b597023e2e69c3802aed67dfc/BetterShotgun/Patches/ShotgunItemPatch.cs#L84C1-L91C10) is causing problems with another mod i have related to shotguns, can you pls check if the user has disabled the CheckAmmoAnimation option and dont run this code in that case.

**Comment by Hypick122** [comment]
Oops, forgot to add the condition. In version 1.1.1 the mistake was corrected
