### ISSUE TITLE
MissfireOff

### ISSUE THREAD

**Issue by TheRealMrKam** [Hypick122/BetterShotgun#8]
### Describe the bug

Hello, i have MissfireOff and it still missfire when i drop it on the ground, is missfire only when you have it in hand ?
(If so can you add the feature to not missfire when you drop it on the ground too ?)
Or is it some incompatibility ?

### Reproducible Test

Drop it on the ground multiple times

**Comment by Hypick122** [comment]
In version 1.1.1 this bug was fixed. If misfires still continue, please report it here
